language: node_js

node_js:
  - "14"
  - "12"

env:
  - REACT_APP_API_KEY=$REACT_APP_API_KEY

script:
  - npm test
  - npm run build

after_success:
  - npm install -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"